### PR TITLE
Don't run upgrades if Umbraco isn't set up #135

### LINKED ISSUE #135: [v9] Contentment crashes Umbraco during initial install
### Which Contentment version are you using?

3.0.0-alpha005

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.0.0

### Bug summary

I'm creating a custom template for Umbraco 9, which among other things will have Contentment installed.

However, installing the Contentment NuGet package will cause Umbraco to fail on startup because it tries to run its upgrades in the Component here: https://github.com/leekelleher/umbraco-contentment/blob/0f60d6a2fd79a24174c5c5388a38c78be40363a2/src/Umbraco.Community.Contentment/Composing/ContentmentComponent.cs#L33-L34

This should probably check the RuntimeLevel before running... Or so I think. Will have a look at a proper fix tomorrow.

### Steps to reproduce

1. Create a blank Umbraco 9 project using dotnet new
2. Before running Umbraco for the first time, install Contentment
3. Then run Umbraco, it will crash and not open the installer

### Expected result / actual result

_No response_

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by arknu**
### Description
Check the RuntimeLevel before attempting to run migrations. Otherwise, Umbraco will crash during initial install.

### Related Issues?
Fixes #135 

### Types of changes
- [ ] Documentation change
- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_

### Checklist

- [x] My code follows the coding style of this project.
- [x] My changes generate no new warnings.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the corresponding documentation.
- [ ] I have read the **[CONTRIBUTING](CONTRIBUTING)** and **[CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)** documents.

### CODE REVIEW

File: src/Umbraco.Community.Contentment/Composing/ContentmentComponent.cs [hunk 1]
```diff
@@ -17,21 +17,27 @@ internal sealed class ContentmentComponent : IComponent
...
             _scopeProvider = scopeProvider;
             _keyValueService = keyValueService;
+            _runtimeState = runtimeState;
         }
 
         public void Initialize()
         {
-            var upgrader = new Upgrader(new ContentmentPlan());
-            upgrader.Execute(_migrationPlanExecutor, _scopeProvider, _keyValueService);
+            if (_runtimeState.Level == Cms.Core.RuntimeLevel.Upgrade || _runtimeState.Level == Cms.Core.RuntimeLevel.Run)
```
Comment (leekelleher) [inline src/Umbraco.Community.Contentment/Composing/ContentmentComponent.cs:36]: I think this can be simplified to `_runtimeState.Level > RuntimeLevel.Install`, but it's totally fine at the moment. 👍

**Comment by leekelleher** [comment]
@arknu I've merged in the fix, thank you! 🌟 

There's a small simplification on the runtime level check, but I can sort that out later.

The other big news that I haven't mentioned yet is that I'm opting for taking a multi-targeted route. The latest work-in-progress is on the [`dev/wip/dotnet-multi-target`](https://github.com/leekelleher/umbraco-contentment/tree/dev/wip/dotnet-multi-target) branch. I'll merge in your fix from this PR.  My aim is to get a release out early next week, as I need to bump the v8 version up to v8.17.0 (once that's released). Everything else (for the v9 version) should be exactly the same as the alpha releases I've done recently. 🤞
